### ISSUE TITLE
Add compiled CSS to dist/

### ISSUE THREAD

**Issue by strarsis** [javan/details-element-polyfill#6]
It would be great if compiled CSS is also provided in `dist/`.
SASS syntax is less common than SCSS, also some use PostCSS.
A syntax agnostic CSS file for further usage would be therefore the best solution.

```css
@charset "UTF-8";
details:not([open]) > *:not(summary) {
  display: none;
}
details > summary {
  display: block;
}
details > summary::before {
  content: "►";
  padding-right: 0.3rem;
  font-size: 0.6rem;
  cursor: default;
}
details[open] > summary::before {
  content: "▼";
}
````

Apparently there is no build script for coffeescript to JS either.

Edit: If you use webpack you can also just import the SASS file, 
it will even work from within a SCSS project, 
you may have to add `.sass` file extension to SASS webpack loader, too:
```scss
@import "~details-element-polyfill/src/details-element-polyfill/polyfill";
````
